import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

export const create = mutation({ args: { name: v.string(), repo: v.string(), defaultBranch: v.string(), checkCommand: v.optional(v.string()), joinCode: v.string() }, handler: async (ctx, args) => ctx.db.insert("rooms", { ...args, createdAt: Date.now() }) });
export const byJoinCode = query({ args: { joinCode: v.string() }, handler: (ctx, args) => ctx.db.query("rooms").withIndex("by_join_code", q => q.eq("joinCode", args.joinCode)).unique() });
export const join = mutation({ args: { roomId: v.id("rooms"), name: v.string(), agent: v.string(), tokenHash: v.string() }, handler: async (ctx, args) => ctx.db.insert("participants", { ...args, joinedAt: Date.now() }) });
export const participantByToken = query({ args: { tokenHash: v.string() }, handler: (ctx, args) => ctx.db.query("participants").withIndex("by_token_hash", q => q.eq("tokenHash", args.tokenHash)).unique() });
export const setIntent = mutation({ args: { roomId: v.id("rooms"), participantId: v.id("participants"), task: v.string(), objective: v.optional(v.string()), expectedPaths: v.array(v.string()), status: v.string() }, handler: async (ctx, args) => { const old = await ctx.db.query("intents").withIndex("by_participant", q => q.eq("participantId", args.participantId)).unique(); if (old) await ctx.db.replace(old._id, { ...args, updatedAt: Date.now() }); else await ctx.db.insert("intents", { ...args, updatedAt: Date.now() }); } });
export const addDecision = mutation({ args: { roomId: v.id("rooms"), participantId: v.id("participants"), title: v.string(), body: v.string() }, handler: (ctx, args) => ctx.db.insert("decisions", { ...args, createdAt: Date.now() }) });
export const updateActivity = mutation({ args: { participantId: v.id("participants"), branch: v.string(), head: v.string(), dirty: v.boolean(), changedPaths: v.array(v.string()) }, handler: async (ctx, args) => { await ctx.db.patch(args.participantId, { branch: args.branch, head: args.head, dirty: args.dirty, changedPaths: args.changedPaths.slice(0, 100) }); } });
export const snapshot = query({ args: { roomId: v.id("rooms") }, handler: async (ctx, args) => ({ room: await ctx.db.get(args.roomId), participants: await ctx.db.query("participants").withIndex("by_room", q => q.eq("roomId", args.roomId)).collect(), intents: await ctx.db.query("intents").withIndex("by_room", q => q.eq("roomId", args.roomId)).collect(), decisions: await ctx.db.query("decisions").withIndex("by_room", q => q.eq("roomId", args.roomId)).collect() }) });
